[package]
name = "webServer"
version = "0.1.0"
authors = ["tiago"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "3.4.0"
serde_json = "1.0"
rand = "0.7"